{{- if .Values.ingress.enabled }}
{{- $fullname := include "ch.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "ch.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-api
                port: { name: http }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port: { name: http }
    {{- end }}
{{- end }}
